name: "Start DAST/ZAP scan at night on scheduler"

on: 
  workflow_dispatch:

  schedule:
    - cron: "15 1 * * *"
  
  push: 
    branches: ["master"]
    
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication 
    steps: 
      - name: Checkout
        uses: actions/checkout@v2 
        
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.1 
        with: 
          target: 'https://upuat.appdevupuat.com'

  upload-report-email: 
    needs: zap_scan 
    if: success() 
    runs-on: mx-self-hosted

  steps:
  # - name: Deploy report 
  # # run: echo "PUblish ZAP-reports" 
  # run: mkdir -p C:\inetpub\wwwroot\cx-allure-reports-web\up\smoke\${{ github.run_number }}
  # 
   - uses: actions/download-artifact@v3 
     with: 
       name: zap_scan
       path: C:\inetpub\wwwroot\cx-allure-reports-web\zap_scan\${{ github.run_number }}

   - name: Send notification 
     run: |
      $body =@" 
        ZAP Scanning Report <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">run</a> for UP is successful <br>
      Related report: <a href="http://10.194.108.90/zap_scan/${{ github.run_number }}"> ${{ github.run_number }}</a>
      "@
      Send-MailMessage -from 'noreplay@metrolinx.com' -To 'v-epam-oleksii.savin@metrolinx.com' -Subject 'Github Actions job result' -Body $body -BodyAsHtml -SmtpServer 'smtp.gotransit.local' 
    # - name: Gererate default.htm for IIS
    # run: | 
    # echo 'cx-allure-reports-web: <br>started from (curent is <a href="http://10.194.108.90/up/smoke/${{ github.run_number }}"> ${{ github.run_number }}</a>) ' > default.htm 
    # cp -r default.htm 'C:\inetpub\wwwroot\cx-allure-reports-web\up\smoke\'
